version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: root
  AfterInstall:
    - location: after_install.sh
      runas: root
  ApplicationStart:
    - location: start_server.sh
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      runas: root

